CREATE TABLE [dbo].[Investor]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[MAInvestorId] VARCHAR(50) NULL,     
	[InvestorApplicationId] int NOT NULL,   
	[PrimaryInvestorID] INT NULL, 
	[Title] VARCHAR(25) NULL,
	[PersonalSalutation] VARCHAR(25) NULL,
	[FirstName] NVARCHAR(50) NULL, 
	[OtherNames] NVARCHAR(250) NULL, 
	[LastName] NVARCHAR(50) NOT NULL, 
	[Superfund-Trust_Name] VARCHAR(150) NULL,
	[CompanyName] VARCHAR(150) NULL,
	[DOB] DATE NOT NULL,     
	[Gender] CHAR(1)  NULL,     
	[Res_UnitNum] NVARCHAR(25) NULL, 
	[Res_Street1] NVARCHAR(50) NOT NULL, 
	[Res_Street2] NVARCHAR(50) NULL, 
	[Res_Street3] NVARCHAR(50) NULL,
	[Res_Street4] NVARCHAR(50) NULL,
	[Res_Street5] NVARCHAR(50) NULL,
	[Res_Postcode] VARCHAR(15) NULL, 
	[Res_Suburb] NVARCHAR(50) NOT NULL, 
	[Res_City] NVARCHAR(50) NOT NULL, 
	[Res_State] NVARCHAR(50) NULL, 
	[Res_Country] VARCHAR(50) NOT NULL, 
	[Bill_UnitNum] NVARCHAR(25) NULL, 
	[Bill_Street1] NVARCHAR(50) NULL, 
	[Bill_Street2] NVARCHAR(50) NULL, 
	[Bill_Street3] NVARCHAR(50) NULL,
	[Bill_Street4] NVARCHAR(50) NULL,
	[Bill_Street5] NVARCHAR(50) NULL,
	[Bill_Postcode] VARCHAR(15) NULL, 
	[Bill_Suburb] NVARCHAR(50) NULL, 
	[Bill_City] NVARCHAR(50) NULL, 
	[Bill_State] NVARCHAR(50) NULL, 
	[Bill_Country] VARCHAR(50) NULL,         
	[Comments] VARCHAR(250) NULL, 
	[PhoneMobile] VARCHAR(50) NULL,
	[PhoneHome] VARCHAR(50) NULL,
	[PhoneWork] VARCHAR(50) NULL, 
	[PhoneOther] VARCHAR(50) NULL, 
	[Email] VARCHAR(50) NULL, 
	[EmailOther] VARCHAR(50) NULL, 
	[ContactComments] VARCHAR(50) NULL,
	[AssquireStatus] VARCHAR(25) NOT NULL, 
	[AppliedDate] DATETIME2 NOT NULL, 
	[AssquireApprovedDate] DATETIME2 NULL, 
	[Created] DATETIME2 NOT NULL, 
	[CreatedBy] VARCHAR(50) NOT NULL, 
	[Updated] DATETIME2 NULL, 
	[UpdatedBy] DATETIME2 NULL, 
)
