CREATE TABLE [dbo].[InvestorApplications] (
    [Id]                                 INT                IDENTITY (1, 1) NOT NULL,
    [EntryDate]                          VARCHAR(25)           NULL,
    [ApplicantType]                      VARCHAR(10)           NULL,
    [Primary_FirstName]                  NVARCHAR (255)     NULL,
    [Primary_OtherNames]                 NVARCHAR (255)     NULL,
    [Primary_LastName]                   NVARCHAR (255)     NULL,
    [Primary_DOB]                        DATETIME           NULL,
	[Primary_AUCitizenStat] VARCHAR(25) NULL,	
    [Primary_Dependants]                 TINYINT                NULL,
    [Other_FirstName]                    NVARCHAR (255)     NULL,
    [Other_OtherNames]                   NVARCHAR (255)     NULL,
    [Other_LastName]                     NVARCHAR (255)     NULL,
    [Other_DOB]                          DATETIME           NULL,
    [Other_Gender]                       VARCHAR(10)           NULL,
    [Other_AUCitizenStat]                VARCHAR(25)     NULL,
    [Other_Dependants]                   TINYINT           NULL,
    [Email]                              VARCHAR(255)     NULL,
    [Mobile]                             VARCHAR(50)     NULL,
    [Res_Street1]                        NVARCHAR (255)     NULL,
    [Res_Street2]                        NVARCHAR (255)     NULL,
    [Res_City]                           NVARCHAR (255)     NULL,
    [Res_PostCode]                       SMALLINT                NULL,
	[Res_State]	VARCHAR(50) NULL,	
    [Res_Country]                        VARCHAR(50)     NULL,
    [YrsCurrAddr]                        TINYINT           NULL,
    [CurrResidStatus]                      VARCHAR(25)           NULL,
    [YrsPrevAddr]                        TINYINT           NULL,
    [PrevResStatus]                      VARCHAR(25)           NULL,
    [CurrOccupType]                      VARCHAR(100)           NULL,
    [CurrEmploymentStatus]               VARCHAR(100)           NULL,
    [YrsCurrEmployer]                    TINYINT           NULL,
    [YrsPrevEmployer]                    TINYINT     NULL,
    [IsSmoker]                           VARCHAR(10)                NULL,
    [HasPrivateHealthIns]                VARCHAR(10)                NULL,
    [CreatedBy]                          NVARCHAR (255)     NULL,
    [Created]                            DATETIMEOFFSET (7) NULL,
    [ModifiedBy]                         NVARCHAR (255)     NULL,
    [Modified]                           DATETIMEOFFSET (7) NULL,
    [RowVersion]                         ROWVERSION         NOT NULL,
    [InvestorApplicant_AssquireInvestor] INT                NULL,
    [InvestorApplication_Gender]         INT                NULL,
    [Primary_IncomeMoAT] VARCHAR(50) NULL, 
    [Other_IncomeMoAT] VARCHAR(50) NULL, 
    [HouseholdIncomeGrossPA] VARCHAR(50) NULL, 
    [LookingLocation] VARCHAR(150) NULL, 
    [FoundLocation] VARCHAR(150) NULL, 
    [Property_Street1] NVARCHAR(255) NULL, 
    [Property_Street2] NVARCHAR(255) NULL, 
    [Property_City] VARCHAR(50) NULL, 
    [Property_State] VARCHAR(50) NULL, 
    [Property_Postcode] SMALLINT NULL, 
    [Property_Country] VARCHAR(50) NULL, 
    [Property_Vendor] NVARCHAR(255) NULL, 
    [EstSpend] VARCHAR(50) NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [InvestorApplication_AssquireInvestor] FOREIGN KEY ([InvestorApplicant_AssquireInvestor]) REFERENCES [dbo].[AssquireInvestors] ([Id]) ON DELETE SET NULL
);

