CREATE TABLE [dbo].[Investor]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [MAId] VARCHAR(50) NULL,     
	[InvestorApplicationId] int NOT NULL,   
	[PrimaryInvestorID] INT NULL, 
	[FirstName] NVARCHAR(50) NULL, 
    [MiddleNames] NVARCHAR(250) NULL, 
    [LastName] NVARCHAR(50) NOT NULL, 
	[Title] VARCHAR(50) NULL, 
    [DOB] DATE NOT NULL,     
    [Gender] INT NOT NULL,     
	[Res_UnitNum] NVARCHAR(25) NULL, 
    [Res_Street1] NVARCHAR(50) NOT NULL, 
    [Res_Street2] NVARCHAR(50) NULL, 
    [Res_Postcode] VARCHAR(15) NULL, 
    [Res_Suburb] NVARCHAR(50) NOT NULL, 
    [Res_State] NVARCHAR(50) NULL, 
    [Res_Country] VARCHAR(50) NOT NULL,         
    [Comments] VARCHAR(250) NULL, 
    [PhoneMobile] VARCHAR(50) NULL, 
    [PhoneOther] VARCHAR(50) NULL, 
    [Email] VARCHAR(50) NULL, 
    [EmailOther] VARCHAR(50) NULL, 
    [ContactComments] VARCHAR(50) NULL,
	[AssquireStatus] VARCHAR(25) NOT NULL, 
    [AppliedDate] DATETIME2 NOT NULL, 
	[AssquireApprovedDate] DATETIME2 NULL, 
	[Created] DATETIME2 NOT NULL, 
    [CreatedBy] VARCHAR(50) NOT NULL, 
    [Updated] DATETIME2 NULL, 
    [UpdatedBy] DATETIME2 NULL, 
)
