CREATE TABLE [dbo].[Property]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[MAId] VARCHAR(50) NULL, 
	[Type] SMALLINT NULL, 
	[UnitNum] VARCHAR(25) NULL, 
	[Street1] VARCHAR(50) NULL, 
	[Street2] VARCHAR(50) NULL, 
	[Street3] VARCHAR(50) NULL, 
	[Street4] VARCHAR(50) NULL, 
	[Street5] VARCHAR(50) NULL,     
	[Suburb] NCHAR(10) NULL, 
	[Postcode] SMALLINT NULL, 
	[State] VARCHAR(15) NULL,
	[PrimaryInvestorId] INT NULL, 
	[Description] VARCHAR(1250) NULL, 
	[Country] VARCHAR(50) NULL, 
	[LocalGov] VARCHAR(50) NULL, 
	[ListPrice] DECIMAL(15, 2) NULL, 
	[AgreedPrice] DECIMAL(15, 2) NULL, 
	[PurchasePrice] DECIMAL(15, 2) NULL, 
	[ListingAgentId] INT NULL, 
	[VendorId] INT NULL, 
	[DevelopmentId] INT NULL, 
	[TitleType] VARCHAR(25) NULL, 
	[Lot] VARCHAR(25) NULL, 
	[Plan] VARCHAR(50) NULL, 
	[Parish] VARCHAR(50) NULL, 
	[CTVolume] VARCHAR(50) NULL, 
	[CTFolio] VARCHAR(50) NULL, 
	[AreaSqm] DECIMAL NULL, 
	[InvestorApplicationId] INT NULL, 
    CONSTRAINT [FK_Property_Investor] FOREIGN KEY ([PrimaryInvestorId]) REFERENCES [Investor]([Id]), 
    CONSTRAINT [FK_Property_InvestorApplications] FOREIGN KEY ([InvestorApplicationId]) REFERENCES [InvestorApplications]([Id])
)
