CREATE TABLE [dbo].[Vendor]
(
	[Id] INT NOT NULL PRIMARY KEY, 
	[MAId] VARCHAR(50) NULL, 
	[PersonalSalutation] VARCHAR(25) NULL,
	[Title] VARCHAR(25) NULL,
	[FirstName] NVARCHAR(50) NULL,     
	[OtherNames] NCHAR(10) NULL, 
	[LastName] NCHAR(10) NULL, 
	[CompanyName] NVARCHAR(50) NULL, 
	[ABN] VARCHAR(15) NULL,
	[ACN] VARCHAR(15) NULL,
	[Website] VARCHAR(255) NULL,	
	[IsPrivateOwner] BIT NULL, 
	[UnitNum] NCHAR(10) NULL, 
	[StreetNum] NCHAR(10) NULL, 
	[Street1] NCHAR(10) NULL, 
	[Street2] NCHAR(10) NULL, 
	[Street3] NCHAR(10) NULL, 
	[Suburb] NCHAR(10) NULL, 
	[Postcode] NCHAR(10) NULL, 
	[State] NCHAR(10) NULL, 
	[Country] VARCHAR(50) NULL,    
	[PhoneMobile] NCHAR(10) NULL, 
	[PhoneOther] NCHAR(10) NULL, 
	[PhoneWork] VARCHAR(50) NULL, 
	[FaxNo] VARCHAR(50) NULL,
	[Email] NCHAR(10) NULL, 
	[EmailOther] NCHAR(10) NULL, 
	[ContactComments] VARCHAR(250) NULL,
	
)
