CREATE VIEW [dbo].[vw_BuyerApplicationsNew]
	AS 
	SELECT 
	ba.Id as [ApplicationId],
	ba.ApplicantType,
	ba.EntryDate,
	ba.EntryId,
	CASE WHEN ( (ba.Primary_Title  IS NULL) OR (LEN(ba.Primary_Title )=0 )) THEN ( CASE WHEN (ba.Primary_Gender LIKE 'FEM%' ) Then 'Ms.' WHEN (ba.Primary_Gender LIKE 'M%' ) Then 'Mr.' Else '' END) WHEN (ba.Primary_Title  = 'ORG') THEN '' ELSE   ba.Primary_Title END  + ' ' + ba.Primary_LastName AS [Primary_Salutation],
	ba.Primary_FirstName,
	ba.Primary_OtherNames,
	ba.Primary_LastName,
	ba.Primary_DOB,
	ba.Email,
	ba.Mobile,
	ba.Primary_HomePhone,
	ba.Primary_Res_Street1,
	ba.Primary_Res_Street2,
	ba.Primary_Res_Suburb,
	ba.Primary_Res_PostCode,
	ba.Primary_Res_State,
	ba.Other_Title, 
	CASE WHEN ( (ba.Primary_Title  IS NULL) OR (LEN(ba.Primary_Title )=0 )) THEN ( CASE WHEN (ba.Primary_Gender LIKE 'FEM%' ) Then 'Ms.' WHEN (ba.Primary_Gender LIKE 'M%' ) Then 'Mr.' Else '' END) ELSE   ba.Primary_Title END  + ' ' + ba.Primary_LastName AS [Other_Salutation],
	ba.Other_FirstName,	
	ba.Other_OtherNames,
	ba.Other_LastName,
	ba.Other_DOB,
	ba.Other_Email,
	ba.Other_Mobile,
	ba.Other_HomePhone,
	ba.Other_Res_Street1,
	ba.Other_Res_Street2,
	ba.Other_Res_Suburb,
	ba.Other_Res_PostCode,
	ba.Other_Res_State,
	ba.EstSpend as [AppliedLimit$],
	NULL as [CondApprovedLimit$],
	NULL as [FinalApprovedLimit$],
	NULL as [MthlyRent],
	NULL as [MthlyDeposit],
	ba.DesiredPropertyAddr,
	ba.CondCreditDecision,
	ba.CondCreditDecisionDate,
	ba.CondCreditDecisionBy,
	ba.CondCreditDecisionInformed,
	ba.CondCreditDecisionInformedBy,
	ba.AutoPreApprovalResult,
	ba.AutoPreApprovalBy,
	ba.AutoPreApprovalDate	
FROM [dbo].[BuyerApplications] ba
JOIN BuyerScoreCard bsc ON bsc.BuyerApplicationId = ba.Id
WHERE ba.CondCreditDecision IS NULL AND ba.CondCreditDecisionDate IS NULL