CREATE VIEW [dbo].[vw_InvestorApplications]
	AS SELECT 
	ia.ApplicantType,
	ia.EntryDate,
	ia.EntryId,
	CASE WHEN ( (ia.Primary_Title  IS NULL) OR (LEN(ia.Primary_Title )=0 )) THEN ( CASE WHEN (ia.Primary_Gender LIKE 'FEM%' ) Then 'Ms.' WHEN (ia.Primary_Gender LIKE 'M%' ) Then 'Mr.' Else '' END) ELSE   ia.Primary_Title END  + ' ' + ia.Primary_LastName AS [Primary_Salutation],
	ia.Primary_FirstName,
	ia.Primary_OtherNames,
	ia.Primary_LastName,
	ia.Primary_DOB,
	ia.Email,
	ia.Mobile,
	ia.Primary_HomePhone,
	ia.Primary_Res_Street1,
	ia.Primary_Res_Street2,
	ia.Primary_Res_Suburb,
	ia.Primary_Res_PostCode,
	ia.Primary_Res_State,
	ia.Other_Title, 
	CASE WHEN ( (ia.Primary_Title  IS NULL) OR (LEN(ia.Primary_Title )=0 )) THEN ( CASE WHEN (ia.Primary_Gender LIKE 'FEM%' ) Then 'Ms.' WHEN (ia.Primary_Gender LIKE 'M%' ) Then 'Mr.' Else '' END) ELSE   ia.Primary_Title END  + ' ' + ia.Primary_LastName AS [Other_Salutation],
	ia.Other_FirstName,	
	ia.Other_OtherNames,
	ia.Other_LastName,
	ia.Other_DOB,
	ia.Other_Email,
	ia.Other_Mobile,
	ia.Other_HomePhone,
	ia.Other_Res_Street1,
	ia.Other_Res_Street2,
	ia.Other_Res_Suburb,
	ia.Other_Res_PostCode,
	ia.Other_Res_State,
	ia.EstSpend as [CondAppliedLimit$],
	ia.DesiredPropertyAddr,
	CASE ia.CondApproved WHEN 1 THEN 'Approved' WHEN 0 THEN 'Rejected' END AS CondApprovedResult,
	ia.CondDecision,
	ia.CondDecisionBy,
	ia.AutoAccepted,
	ia.AutoAcceptedBy,
	ia.AutoAcceptedInformed,
	ia.AutoAcceptedInformedBy,
	ia.AutoRejected,
	ia.AutoRejecetedBy,
	ia.AutoRejectedInformed,
	ia.AutoRejectedInformedBy	 	 	
	FROM [dbo].[InvestorApplications] ia
