CREATE VIEW [dbo].[vw_InvestorApplications]
	AS SELECT 
	ia.Id as [ApplicationId],
	ia.ApplicantType,
	ia.EntryDate,
	ia.EntryId,
	CASE WHEN ( (ia.Primary_Title  IS NULL) OR (LEN(ia.Primary_Title )=0 )) THEN ( CASE WHEN (ia.Primary_Gender LIKE 'FEM%' ) Then 'Ms.' WHEN (ia.Primary_Gender LIKE 'M%' ) Then 'Mr.' Else '' END) ELSE   ia.Primary_Title END  + ' ' + ia.Primary_LastName AS [Primary_Salutation],
	ia.Primary_Title,
	ia.Primary_FirstName,
	ia.Primary_OtherNames,
	ia.Primary_LastName,
	ia.Primary_DOB,
	ia.Email,
	ia.Mobile,
	ia.Primary_HomePhone,
	ia.Primary_Res_Street1,
	ia.Primary_Res_Street2,
	ia.Primary_Res_Suburb,
	ia.Primary_Res_PostCode,
	ia.Primary_Res_State,
	ia.Other_Title, 
	CASE WHEN ( (ia.Other_Title  IS NULL) OR (LEN(ia.Other_Title )=0 )) THEN ( CASE WHEN (ia.Other_Gender LIKE 'FEM%' ) Then 'Ms.' WHEN (ia.Other_Gender LIKE 'M%' ) Then 'Mr.' Else '' END) ELSE   ia.Other_Title END  + ' ' + ia.Other_LastName AS [Other_Salutation],
	ia.Other_FirstName,	
	ia.Other_OtherNames,
	ia.Other_LastName,
	ia.Other_DOB,
	ia.Other_Email,
	ia.Other_Mobile,
	ia.Other_HomePhone,
	ia.Other_Res_Street1,
	ia.Other_Res_Street2,
	ia.Other_Res_Suburb,
	ia.Other_Res_PostCode,
	ia.Other_Res_State,
	ia.EstSpend as [CondAppliedLimit$],
	ia.DesiredPropertyAddr,
	ia.CondCreditDecision,
	ia.CondCreditDecisionDate,
	ia.CondDecisionBy,
	ia.AutoAccepted,
	ia.AutoAcceptedBy,
	ia.AutoRejected,
	ia.AutoRejectedBy,
	ia.CondCreditDecisionInformed,
	ia.CondCreditDecisionInformedBy,
	ia.AppAckLetterSent	 	
	FROM [dbo].[InvestorApplications] ia
